FROM continuumio/miniconda3
LABEL maintainer="Sylvain Anderegg"

RUN conda update conda
RUN conda install flask
RUN pip install docker

WORKDIR /home/app

ENV FLASK_APP=director.py
ENV FLASK_DEBUG=1
ENV REGISTRY_AUTH = ''
ENV REGISTRY_USER = ''
ENV REGISTRY_PW = ''
ENV REGISTRY_URL = ''

EXPOSE 8001
VOLUME /home/app

ENTRYPOINT [ "flask", "run", "--host=0.0.0.0", "--port=8001"]
