FROM continuumio/miniconda3
LABEL maintainer="Manuel Guidon <guidon@itis.ethz.ch"

ARG modelsdir
ARG models_outdir

RUN conda update conda
RUN conda install networkx sqlalchemy psycopg2
RUN conda install -c conda-forge celery

RUN pip install sqlalchemy-json docker pika

EXPOSE 8000

WORKDIR /work/sidecar

COPY $modelsdir $models_outdir

ADD ./sidecar/*.py ./

ENV PYTHONPATH=$models_outdir
ENTRYPOINT celery -A sidecar worker -c 1 --loglevel=info




