#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# pull the current tested build
export DOCKER_IMAGE_TAG=$(exec ci/github/helpers/build_docker_image_tag)
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# these variable must be available securely from github
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# re-tag build to master-latest
export DOCKER_IMAGE_TAG=master-latest
make push-version

# re-tag build to master-DATE.github.GIT_SHA
export DOCKER_IMAGE_TAG=master-$(date +"%Y-%m-%d").githubactions.$(git rev-parse HEAD)
make push-version

# show update of images on system
echo "## After push"
make info-images
