#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# these variable must be available securely from github
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# only upstream is allowed to push to itisfoundation repo
current_fork=$(echo "${GITHUB_REPOSITORY%/*}" | tr '[:upper:]' '[:lower:]')
if [ $current_fork != "itisfoundation" ] &&\
    ([ ! -v DOCKER_REGISTRY ] || [ -z $DOCKER_REGISTRY ] || [ "$DOCKER_REGISTRY" = "itisfoundation" ]); then
    echo "## ERROR: it is not allowed to push to the main dockerhub repository from a fork!"
    echo "## Please adapt your CI-defined environs (DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_REGISTRY)"
    exit 1
fi

# pull the tagged staging build
# find the docker image tag
export TAG="${GITHUB_REF##*/}"
export ORG=${DOCKER_REGISTRY}
export REPO="webserver"
# staging-github-DATE.GIT_SHA
export TAG_PATTERN="^staging-github-.+\..+"
export DOCKER_IMAGE_TAG=$(./ci/helpers/find_staging_version | awk 'END{print}') || exit $?
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# re-tag staging to {TAG}-DATE.GIT_SHA
export DOCKER_IMAGE_TAG=${TAG}-$(date +"%Y-%m-%d").$(git rev-parse HEAD)
make push-version push-latest

echo "## After push"
make info-images
