#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# pull the tagged master build
export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# these variable must be available securely from github
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# re-tag build
export DOCKER_IMAGE_TAG=staging-github-latest
make push-version

# re-tag master to staging-github-DATE.GIT_SHA
export DOCKER_IMAGE_TAG=staging-github-$(date +"%Y-%m-%d").$(git rev-parse HEAD)
make push-version

echo "## After push"
make info-images
