#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

FOLDER_CHECKS=(.py .pylintrc .travis.yml)

before_install() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ci/helpers/show_system_version.bashs
    fi
}

install() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ci/helpers/ensure_python_pip.bash
        pip3 install pylint~=2.0
        # Minimal packages to pass linter
        pip install celery docker
    fi
}

before_script() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip list -v
        pylint --version
    fi
}

script() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        make pylint
    else
        echo "No changes detected. Skipping linting of python code."
    fi
}

after_success() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        echo "linting successful"
    fi
}

after_failure() {
    echo "failure... you can always write something more interesting here..."
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
