# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class HealthInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, status=None, version=None, last_access=None):  # noqa: E501
        """HealthInfo - a model defined in OpenAPI

        :param name: The name of this HealthInfo.  # noqa: E501
        :type name: str
        :param status: The status of this HealthInfo.  # noqa: E501
        :type status: str
        :param version: The version of this HealthInfo.  # noqa: E501
        :type version: str
        :param last_access: The last_access of this HealthInfo.  # noqa: E501
        :type last_access: float
        """
        self.openapi_types = {
            'name': 'str',
            'status': 'str',
            'version': 'str',
            'last_access': 'float'
        }

        self.attribute_map = {
            'name': 'name',
            'status': 'status',
            'version': 'version',
            'last_access': 'last_access'
        }

        self._name = name
        self._status = status
        self._version = version
        self._last_access = last_access

    @classmethod
    def from_dict(cls, dikt) -> 'HealthInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthInfo of this HealthInfo.  # noqa: E501
        :rtype: HealthInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this HealthInfo.


        :return: The name of this HealthInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HealthInfo.


        :param name: The name of this HealthInfo.
        :type name: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this HealthInfo.


        :return: The status of this HealthInfo.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this HealthInfo.


        :param status: The status of this HealthInfo.
        :type status: str
        """

        self._status = status

    @property
    def version(self):
        """Gets the version of this HealthInfo.


        :return: The version of this HealthInfo.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this HealthInfo.


        :param version: The version of this HealthInfo.
        :type version: str
        """

        self._version = version

    @property
    def last_access(self):
        """Gets the last_access of this HealthInfo.


        :return: The last_access of this HealthInfo.
        :rtype: float
        """
        return self._last_access

    @last_access.setter
    def last_access(self, last_access):
        """Sets the last_access of this HealthInfo.


        :param last_access: The last_access of this HealthInfo.
        :type last_access: float
        """

        self._last_access = last_access
