merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: default
    batch_size: 1

    queue_conditions:
      - label=🤖-automerge
      - label!=🤖-do-not-merge
      - base=master
      - -draft
      - -conflict
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"

    merge_conditions: # (identical to queue_conditions)
      - label=🤖-automerge
      - label!=🤖-do-not-merge
      - base=master
      - -draft
      - -conflict
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
merge_protections_settings:
  reporting_method: check-runs
