# coding: utf-8

"""
    simcore-service-storage API

    API definition for simcore-service-storage service  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: support@simcore.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import datetime
import unittest

import simcore_service_storage_sdk
from simcore_service_storage_sdk.models.presigned_link_enveloped import (  # noqa: E501
    PresignedLinkEnveloped,
)
from simcore_service_storage_sdk.rest import ApiException


class TestPresignedLinkEnveloped(unittest.TestCase):
    """PresignedLinkEnveloped unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PresignedLinkEnveloped
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = simcore_service_storage_sdk.models.presigned_link_enveloped.PresignedLinkEnveloped()  # noqa: E501
        if include_optional:
            return PresignedLinkEnveloped(data={"link": "example_link"}, error=null)
        else:
            return PresignedLinkEnveloped(
                data={"link": "example_link"},
                error=null,
            )

    def testPresignedLinkEnveloped(self):
        """Test PresignedLinkEnveloped"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
