# coding: utf-8

"""
    simcore-service-storage API

    API definition for simcore-service-storage service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@simcore.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import simcore_service_storage_sdk
from simcore_service_storage_sdk.models.presigned_link_type import PresignedLinkType  # noqa: E501
from simcore_service_storage_sdk.rest import ApiException


class TestPresignedLinkType(unittest.TestCase):
    """PresignedLinkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresignedLinkType(self):
        """Test PresignedLinkType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = simcore_service_storage_sdk.models.presigned_link_type.PresignedLinkType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
