# coding: utf-8

"""
    dsm-api

    dsm api  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "simcore_storage_sdk"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]
REQUIRES.append("aiohttp")

setup(
    name=NAME,
    version=VERSION,
    description="client sdk for simcore-service-storage",
    author_email="",
    url="https://github.com/mguidon/aiohttp-dsm/tree/master/data-storage-manager-sdk/python",
    keywords=["OpenAPI", "OpenAPI-Generator", "dsm-api"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    client sdk for simcore-service-storage  # noqa: E501
    """
)
