"""new group_classifiers table

Revision ID: 01073b43fc74
Revises: f4fda75c0df0
Create Date: 2020-08-19 20:40:02.610105+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01073b43fc74"
down_revision = "f4fda75c0df0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_classifiers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("gid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gid"],
            ["groups.gid"],
            name="fk_group_classifiers_gid_to_groups_gid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="group_classifiers_pkey"),
        sa.UniqueConstraint("gid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_classifiers")
    # ### end Alembic commands ###
