"""update foreign key actions

Revision ID: 05b016148d79
Revises: b949bba5bbcf
Create Date: 2026-01-14 10:17:59.510305+00:00

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "05b016148d79"
down_revision = "b949bba5bbcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_conversation_messages_user_primary_gid"), "conversation_messages", type_="foreignkey")
    op.create_foreign_key(
        "fk_conversation_messages_user_primary_gid",
        "conversation_messages",
        "groups",
        ["user_group_id"],
        ["gid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("fk_conversations_user_primary_gid"), "conversations", type_="foreignkey")
    op.create_foreign_key(
        "fk_conversations_user_primary_gid",
        "conversations",
        "groups",
        ["user_group_id"],
        ["gid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_conversations_user_primary_gid", "conversations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_conversations_user_primary_gid"),
        "conversations",
        "groups",
        ["user_group_id"],
        ["gid"],
        ondelete="SET NULL",
    )
    op.drop_constraint("fk_conversation_messages_user_primary_gid", "conversation_messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_conversation_messages_user_primary_gid"),
        "conversation_messages",
        "groups",
        ["user_group_id"],
        ["gid"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
