"""adding last_heartbeat_at to service_runs table 3

Revision ID: 182f07e21b87
Revises: a9c5b9752af0
Create Date: 2023-08-24 12:57:36.745691+00:00

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "182f07e21b87"
down_revision = "a9c5b9752af0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resource_tracker_service_runs",
        "stopped_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resource_tracker_service_runs",
        "stopped_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###
