"""new comp_tasks errors column

Revision ID: 1c84432e5dbb
Revises: 99f9b200801c
Create Date: 2022-04-25 15:32:36.553853+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c84432e5dbb"
down_revision = "99f9b200801c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comp_tasks", sa.Column("errors", postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comp_tasks", "errors")
    # ### end Alembic commands ###
