"""added folders tables

Revision ID: 21699ee569a7
Revises: 056ed0eb1ba6
Create Date: 2024-07-30 13:38:57.694754+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21699ee569a7"
down_revision = "056ed0eb1ba6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), server_default="", nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["groups.gid"],
            name="fk_folders_to_groups_gid",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "folders_access_rights",
        sa.Column("folder_id", sa.BigInteger(), nullable=False),
        sa.Column("gid", sa.BigInteger(), nullable=False),
        sa.Column("traversal_parent_id", sa.BigInteger(), nullable=True),
        sa.Column("original_parent_id", sa.BigInteger(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("write", sa.Boolean(), nullable=False),
        sa.Column("delete", sa.Boolean(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name="fk_folders_access_rights_to_folders_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gid"],
            ["groups.gid"],
            name="fk_folders_access_rights_to_groups_gid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original_parent_id"],
            ["folders.id"],
            name="fk_folders_to_folders_id_via_original_parent_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["traversal_parent_id"],
            ["folders.id"],
            name="fk_folders_to_folders_id_via_traversal_parent_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("folder_id", "gid", name="folders_access_rights_pk"),
    )
    op.create_table(
        "folders_to_projects",
        sa.Column("folder_id", sa.BigInteger(), nullable=False),
        sa.Column("project_uuid", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name="fk_folders_to_projects_to_folders_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"],
            ["projects.uuid"],
            name="fk_folders_to_projects_to_projects_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "folder_id", "project_uuid", name="projects_to_folder_pk"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("folders_to_projects")
    op.drop_table("folders_access_rights")
    op.drop_table("folders")
    # ### end Alembic commands ###
