"""add template_type to projects

Revision ID: 219608f5a9c3
Revises: 0d52976dc616
Create Date: 2025-05-13 11:21:42.108547+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "219608f5a9c3"
down_revision = "0d52976dc616"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    project_template_type = sa.Enum(
        "TEMPLATE", "TUTORIAL", "HYPERTOOL", name="projecttemplatetype"
    )
    project_template_type.create(op.get_bind())

    # Then add column using the enum type
    op.add_column(
        "projects",
        sa.Column(
            "template_type",
            project_template_type,
            nullable=True,
            default=None,
        ),
    )
    # Update existing template projects
    op.execute("UPDATE projects SET template_type='TEMPLATE' WHERE type='TEMPLATE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "template_type")
    # Drop the enum type after dropping the column
    sa.Enum(name="projecttemplatetype").drop(op.get_bind())
    # ### end Alembic commands ###
