"""add user id in comp_pipeline

Revision ID: 2a53a160c738
Revises: f73fb7d7b9b8
Create Date: 2021-05-10 15:37:04.506813+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a53a160c738"
down_revision = "f73fb7d7b9b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comp_pipeline", sa.Column("user_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "fk_user_to_comp_pipeline_id_users",
        "comp_pipeline",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_to_comp_pipeline_id_users", "comp_pipeline", type_="foreignkey"
    )
    op.drop_column("comp_pipeline", "user_id")
    # ### end Alembic commands ###
