"""add deprecated submit column

Revision ID: 307017ee1a49
Revises: 1e3c9c804fec
Create Date: 2025-01-06 12:53:51.604189+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307017ee1a49'
down_revision = '1e3c9c804fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comp_tasks', sa.Column('submit', sa.DateTime(timezone=True), server_default=sa.text("'1900-01-01T00:00:00Z'::timestamptz"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comp_tasks', 'submit')
    # ### end Alembic commands ###
