"""new user privacy columns

Revision ID: 38c9ac332c58
Revises: e5555076ef50
Create Date: 2024-12-05 14:29:27.739650+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38c9ac332c58"
down_revision = "e5555076ef50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "privacy_hide_fullname",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "privacy_hide_email",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "privacy_hide_email")
    op.drop_column("users", "privacy_hide_fullname")
    # ### end Alembic commands ###
