"""add override_services_specifications

Revision ID: 38fe651b4196
Revises: add0afaaf728
Create Date: 2023-06-23 11:37:04.833354+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38fe651b4196"
down_revision = "add0afaaf728"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups_extra_properties",
        sa.Column(
            "override_services_specifications",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups_extra_properties", "override_services_specifications")
    # ### end Alembic commands ###
