"""add override_services_specifications

Revision ID: 38fe651b4196
Revises: 417f9eb848ce
Create Date: 2023-06-23 11:37:04.833354+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38fe651b4196"
down_revision = "417f9eb848ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups_extra_properties",
        sa.Column(
            "override_services_specifications",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
    groups_extra_properties_table = sa.table(
        "groups_extra_properties",
        sa.column("group_id"),
        sa.column("node_id"),
        sa.column("created"),
        sa.column("modified"),
        sa.column("override_services_specifications"),
    )

    # default to false
    op.execute(
        groups_extra_properties_table.update().values(
            override_services_specifications=False
        )
    )
    # # set to non nullable
    op.alter_column(
        "groups_extra_properties", "override_services_specifications", nullable=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups_extra_properties", "override_services_specifications")
    # ### end Alembic commands ###
