"""preparation for osparc.io migration

Revision ID: 47dc5c0a138e
Revises: 4f6fd2586491
Create Date: 2025-05-19 14:55:15.889813+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "47dc5c0a138e"
down_revision = "4f6fd2586491"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zzz_resource_tracker_service_runs__osparc_io_archive_202508",
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("service_run_id", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.BigInteger(), nullable=True),
        sa.Column("wallet_name", sa.String(), nullable=True),
        sa.Column("pricing_plan_id", sa.BigInteger(), nullable=True),
        sa.Column("pricing_unit_id", sa.BigInteger(), nullable=True),
        sa.Column("pricing_unit_cost_id", sa.BigInteger(), nullable=True),
        sa.Column("pricing_unit_cost", sa.Numeric(scale=2), nullable=True),
        sa.Column("simcore_user_agent", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_name", sa.String(), nullable=False),
        sa.Column("parent_project_id", sa.String(), nullable=False),
        sa.Column("root_parent_project_id", sa.String(), nullable=False),
        sa.Column("root_parent_project_name", sa.String(), nullable=False),
        sa.Column("parent_node_id", sa.String(), nullable=False),
        sa.Column("root_parent_node_id", sa.String(), nullable=False),
        sa.Column("service_key", sa.String(), nullable=False),
        sa.Column("service_version", sa.String(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "COMPUTATIONAL_SERVICE",
                "DYNAMIC_SERVICE",
                name="resourcetrackerservicetypeosparciohistory",
            ),
            nullable=False,
        ),
        sa.Column(
            "service_resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "service_additional_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "service_run_status",
            sa.Enum(
                "RUNNING",
                "SUCCESS",
                "ERROR",
                name="resourcetrackerservicerunstatusosparciohistory",
            ),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_run_status_msg", sa.String(), nullable=True),
        sa.Column("missed_heartbeat_counter", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("product_name", "service_run_id"),
    )
    op.create_index(
        op.f(
            "ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_started_at"
        ),
        "zzz_resource_tracker_service_runs__osparc_io_archive_202508",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_wallet_id"
        ),
        "zzz_resource_tracker_service_runs__osparc_io_archive_202508",
        ["wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_user_id"),
        "zzz_resource_tracker_service_runs__osparc_io_archive_202508",
        ["user_id"],
        unique=False,
    )
    op.drop_index("ix_projects_comments_project_uuid", table_name="projects_comments")
    op.drop_table("projects_comments")
    op.drop_constraint("api_keys_user_id_fkey", "api_keys", type_="foreignkey")
    op.create_foreign_key(
        "fk_api_keys_to_user_id",
        "api_keys",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("user_confirmation_fkey", "confirmations", type_="foreignkey")
    op.create_foreign_key(
        "user_confirmation_fkey",
        "confirmations",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "file_meta_data",
        "user_id",
        existing_type=sa.VARCHAR(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.create_foreign_key(
        "fk_file_meta_data_user_id_users",
        "file_meta_data",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_new_folders_to_folders_id", "folders_v2", type_="foreignkey")
    op.drop_constraint("fk_new_folders_to_groups_gid", "folders_v2", type_="foreignkey")
    op.create_foreign_key(
        "fk_new_folders_to_folders_id",
        "folders_v2",
        "folders_v2",
        ["parent_folder_id"],
        ["folder_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "fk_new_folders_to_groups_gid",
        "folders_v2",
        "groups",
        ["created_by_gid"],
        ["gid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_payments_autorecharge_id_wallets",
        "payments_autorecharge",
        "wallets",
        ["wallet_id"],
        ["wallet_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_payments_methods_to_user_id",
        "payments_methods",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_payments_methods_to_wallet_id",
        "payments_methods",
        "wallets",
        ["wallet_id"],
        ["wallet_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_payments_transactions_to_products_name",
        "payments_transactions",
        "products",
        ["product_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_payments_transactions_to_user_id",
        "payments_transactions",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_payments_transactions_to_wallet_id",
        "payments_transactions",
        "wallets",
        ["wallet_id"],
        ["wallet_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_service_runs_to_product_name",
        "resource_tracker_service_runs",
        "products",
        ["product_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("tokens_user_id_fkey", "tokens", type_="foreignkey")
    op.create_foreign_key(
        "fk_tokens_to_user_id",
        "tokens",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tokens_to_user_id", "tokens", type_="foreignkey")
    op.create_foreign_key("tokens_user_id_fkey", "tokens", "users", ["user_id"], ["id"])
    op.drop_constraint(
        "fk_service_runs_to_product_name",
        "resource_tracker_service_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_payments_transactions_to_wallet_id",
        "payments_transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_payments_transactions_to_user_id",
        "payments_transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_payments_transactions_to_products_name",
        "payments_transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_payments_methods_to_wallet_id", "payments_methods", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_payments_methods_to_user_id", "payments_methods", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_payments_autorecharge_id_wallets",
        "payments_autorecharge",
        type_="foreignkey",
    )
    op.drop_constraint("fk_new_folders_to_groups_gid", "folders_v2", type_="foreignkey")
    op.drop_constraint("fk_new_folders_to_folders_id", "folders_v2", type_="foreignkey")
    op.create_foreign_key(
        "fk_new_folders_to_groups_gid",
        "folders_v2",
        "groups",
        ["created_by_gid"],
        ["gid"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_new_folders_to_folders_id",
        "folders_v2",
        "folders_v2",
        ["parent_folder_id"],
        ["folder_id"],
    )
    op.drop_constraint(
        "fk_file_meta_data_user_id_users", "file_meta_data", type_="foreignkey"
    )
    op.alter_column(
        "file_meta_data",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_constraint("user_confirmation_fkey", "confirmations", type_="foreignkey")
    op.create_foreign_key(
        "user_confirmation_fkey",
        "confirmations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_api_keys_to_user_id", "api_keys", type_="foreignkey")
    op.create_foreign_key(
        "api_keys_user_id_fkey",
        "api_keys",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "projects_comments",
        sa.Column("comment_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("project_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("contents", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"],
            ["projects.uuid"],
            name="fk_projects_comments_project_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_projects_comments_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("comment_id", name="projects_comments_pkey"),
    )
    op.create_index(
        "ix_projects_comments_project_uuid",
        "projects_comments",
        ["project_uuid"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_user_id"),
        table_name="zzz_resource_tracker_service_runs__osparc_io_archive_202508",
    )
    op.drop_index(
        op.f(
            "ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_wallet_id"
        ),
        table_name="zzz_resource_tracker_service_runs__osparc_io_archive_202508",
    )
    op.drop_index(
        op.f(
            "ix_zzz_resource_tracker_service_runs__osparc_io_archive_202508_started_at"
        ),
        table_name="zzz_resource_tracker_service_runs__osparc_io_archive_202508",
    )
    op.drop_table("zzz_resource_tracker_service_runs__osparc_io_archive_202508")
    # ### end Alembic commands ###
