"""add last scheduled time

Revision ID: 4885182f6206
Revises: 8e1f83486be7
Create Date: 2024-11-22 15:50:17.798131+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4885182f6206"
down_revision = "8e1f83486be7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comp_runs",
        sa.Column("last_scheduled", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comp_runs", "last_scheduled")
    # ### end Alembic commands ###
