"""new service_vendor_secrets table

Revision ID: 51caf4bb77d3
Revises: 0c084cb1091c
Create Date: 2023-05-23 15:21:52.266984+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "51caf4bb77d3"
down_revision = "0c084cb1091c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services_vendor_secrets",
        sa.Column("service_key", sa.String(), nullable=False),
        sa.Column("service_from_version", sa.String(), nullable=False),
        sa.Column(
            "secrets_map",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["service_key", "service_from_version"],
            ["services_meta_data.key", "services_meta_data.version"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "service_key", "service_from_version", name="services_vendor_secrets_pk"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("services_vendor_secrets")
    # ### end Alembic commands ###
