"""Add function access rights

Revision ID: 53236b6476f3
Revises: 4e7d8719855b
Create Date: 2025-05-27 07:36:17.252224+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "53236b6476f3"
down_revision = "4e7d8719855b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funcapi_function_job_collections_access_rights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "function_job_collection_uuid",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("write", sa.Boolean(), nullable=True),
        sa.Column("execute", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "user_id IS NULL AND group_id IS NOT NULL OR user_id IS NOT NULL AND group_id IS NULL",
            name="ck_user_or_group_exclusive",
        ),
        sa.ForeignKeyConstraint(
            ["function_job_collection_uuid"],
            ["funcapi_function_job_collections.uuid"],
            name="fk_func_access_to_func_job_colls_to_func_job_coll_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.gid"],
            name="fk_func_access_to_groups_group_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_func_access_to_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "group_id",
            name="uq_funcapi_function_job_colls_access_rights_user_group",
        ),
    )
    op.create_table(
        "funcapi_function_jobs_access_rights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("function_job_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("write", sa.Boolean(), nullable=True),
        sa.Column("execute", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "user_id IS NULL AND group_id IS NOT NULL OR user_id IS NOT NULL AND group_id IS NULL",
            name="ck_user_or_group_exclusive",
        ),
        sa.ForeignKeyConstraint(
            ["function_job_uuid"],
            ["funcapi_function_jobs.uuid"],
            name="fk_func_access_to_func_jobs_to_func_job_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.gid"],
            name="fk_func_access_to_groups_group_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_func_access_to_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "group_id",
            name="uq_funcapi_function_jobs_access_rights_user_group",
        ),
    )
    op.create_table(
        "funcapi_functions_access_rights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("function_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("write", sa.Boolean(), nullable=True),
        sa.Column("execute", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "user_id IS NULL AND group_id IS NOT NULL OR user_id IS NOT NULL AND group_id IS NULL",
            name="ck_user_or_group_exclusive",
        ),
        sa.ForeignKeyConstraint(
            ["function_uuid"],
            ["funcapi_functions.uuid"],
            name="fk_func_access_to_func_to_func_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.gid"],
            name="fk_func_access_to_groups_group_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_func_access_to_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "group_id", name="uq_funcapi_functions_access_rights_user_group"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("funcapi_functions_access_rights")
    op.drop_table("funcapi_function_jobs_access_rights")
    op.drop_table("funcapi_function_job_collections_access_rights")
    # ### end Alembic commands ###
