"""users privacy table

Revision ID: 590cbd7e27bf
Revises: e05bdc5b3c7b
Create Date: 2024-12-04 17:15:55.093862+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "590cbd7e27bf"
down_revision = "e05bdc5b3c7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_privacy",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "hide_email", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "hide_fullname",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_privacy")
    # ### end Alembic commands ###
