"""introduce data_deleted in projects_to_jobs table

Revision ID: 5b998370916a
Revises: 5679165336c8
Create Date: 2025-08-11 13:58:38.424398+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b998370916a"
down_revision = "5679165336c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects_to_jobs",
        sa.Column("storage_data_deleted", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects_to_jobs", "storage_data_deleted")
    # ### end Alembic commands ###
