"""new invoice_url column in payments_transaction table

Revision ID: 7777d181dc1f
Revises: 542e6ee8a8ea
Create Date: 2023-10-16 16:19:26.657533+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7777d181dc1f"
down_revision = "542e6ee8a8ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments_transactions", sa.Column("invoice_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments_transactions", "invoice_url")
    # ### end Alembic commands ###
