"""removing resource usage containers table

Revision ID: 77fce87f1474
Revises: fa26ab3555c8
Create Date: 2023-08-26 14:08:26.154412+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77fce87f1474"
down_revision = "fa26ab3555c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_resource_tracker_container_product_name",
        table_name="resource_tracker_container",
    )
    op.drop_index(
        "ix_resource_tracker_container_prometheus_last_scraped",
        table_name="resource_tracker_container",
    )
    op.drop_index(
        "ix_resource_tracker_container_user_id", table_name="resource_tracker_container"
    )
    op.drop_table("resource_tracker_container")
    # ### end Alembic commands ###
    sa.Enum(name="containerclassification").drop(op.get_bind(), checkfirst=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_tracker_container",
        sa.Column("container_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("product_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "service_settings_reservation_additional_info",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "container_cpu_usage_seconds_total",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "prometheus_created",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "prometheus_last_scraped",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("project_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("node_label", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("instance", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("project_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("service_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("service_version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cpu_limit",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("memory_limit", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "classification",
            postgresql.ENUM(
                "DYNAMIC_SIDECAR", "USER_SERVICE", name="containerclassification"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("container_id", name="resource_tracker_container_pkey"),
    )
    op.create_index(
        "ix_resource_tracker_container_user_id",
        "resource_tracker_container",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_resource_tracker_container_prometheus_last_scraped",
        "resource_tracker_container",
        ["prometheus_last_scraped"],
        unique=False,
    )
    op.create_index(
        "ix_resource_tracker_container_product_name",
        "resource_tracker_container",
        ["product_name"],
        unique=False,
    )
    # ### end Alembic commands ###
