"""adds services_environments table

Revision ID: 799a81a85dd1
Revises: e84904303e2b
Create Date: 2023-02-06 18:03:13.950937+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "799a81a85dd1"
down_revision = "e84904303e2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services_environments",
        sa.Column("service_key", sa.String(), nullable=False),
        sa.Column("gid", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "osparc_environments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["gid"],
            ["groups.gid"],
            name="fk_services_environments_gid_groups",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_key", "gid", name="services_environments_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("services_environments")
    # ### end Alembic commands ###
