"""new users.privacy_hide_username column

Revision ID: 8403acca8759
Revises: f7f3c835f38a
Create Date: 2025-03-20 14:08:48.321587+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8403acca8759"
down_revision = "f7f3c835f38a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "privacy_hide_username",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "privacy_hide_username")
    # ### end Alembic commands ###
