"""adding last_heartbeat_at to service_runs table

Revision ID: 8cdd64202e6c
Revises: e987caaec81b
Create Date: 2023-08-24 07:18:16.514920+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8cdd64202e6c"
down_revision = "e987caaec81b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_tracker_service_runs",
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_tracker_service_runs", "last_heartbeat_at")
    # ### end Alembic commands ###
