"""delete projects deletes project_vc references

Revision ID: 979b2c051d4f
Revises: a2a020b67bd2
Create Date: 2021-09-15 18:51:24.519259+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "979b2c051d4f"
down_revision = "a2a020b67bd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_projects_vc_repos_project_uuid", "projects_vc_repos", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_projects_vc_repos_project_uuid",
        "projects_vc_repos",
        "projects",
        ["project_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_projects_vc_repos_project_uuid", "projects_vc_repos", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_projects_vc_repos_project_uuid",
        "projects_vc_repos",
        "projects",
        ["project_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
