"""changes props in projects version control

Revision ID: 9a398acd2bb3
Revises: a2a020b67bd2
Create Date: 2021-09-15 09:47:52.604419+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a398acd2bb3"
down_revision = "a2a020b67bd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "projects_vc_tags", ["repo_id"])
    op.create_unique_constraint(None, "projects_vc_tags", ["commit_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects_vc_tags", type_="unique")
    op.drop_constraint(None, "projects_vc_tags", type_="unique")
    # ### end Alembic commands ###
