"""add is directory to file meta data table

Revision ID: 9ee58100b5ee
Revises: 52cf00912ad9
Create Date: 2023-06-22 09:49:50.603888+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ee58100b5ee"
down_revision = "52cf00912ad9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file_meta_data",
        sa.Column(
            "is_directory",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_meta_data", "is_directory")
    # ### end Alembic commands ###
