"""adding last_heartbeat_at to service_runs table 2

Revision ID: a9c5b9752af0
Revises: 8cdd64202e6c
Create Date: 2023-08-24 12:53:12.719006+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9c5b9752af0"
down_revision = "8cdd64202e6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resource_tracker_service_runs",
        "wallet_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "resource_tracker_service_runs",
        "pricing_plan_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.alter_column(
        "resource_tracker_service_runs",
        "pricing_detail_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resource_tracker_service_runs",
        "pricing_detail_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "resource_tracker_service_runs",
        "pricing_plan_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "resource_tracker_service_runs",
        "wallet_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###
