"""modify conversations

Revision ID: b566f1b29012
Revises: 5679165336c8
Create Date: 2025-08-14 15:02:54.784186+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b566f1b29012"
down_revision = "5679165336c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "extra_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("support_standard_group_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        "fk_products_support_standard_group_id",
        "products",
        "groups",
        ["support_standard_group_id"],
        ["gid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )

    op.execute(
        """
        ALTER TYPE conversationtype ADD VALUE 'SUPPORT';
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_products_support_standard_group_id", "products", type_="foreignkey"
    )
    op.drop_column("products", "support_standard_group_id")
    op.drop_column("conversations", "extra_context")
    # ### end Alembic commands ###
