"""new user privacy columns

Revision ID: cc0e49c38d02
Revises: e05bdc5b3c7b
Create Date: 2024-12-05 13:59:09.509554+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc0e49c38d02"
down_revision = "e05bdc5b3c7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "privacy_hide_fullname",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "privacy_hide_email",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "privacy_hide_email")
    op.drop_column("users", "privacy_hide_fullname")
    # ### end Alembic commands ###
