"""add indexes

Revision ID: cf8f743fd0b7
Revises: 48604dfdc5f4
Create Date: 2025-04-04 09:46:38.853675+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf8f743fd0b7"
down_revision = "48604dfdc5f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_to_groups_gid", "project_to_groups", ["gid"], unique=False
    )
    op.create_index(
        "idx_projects_last_change_date_desc",
        "projects",
        ["last_change_date"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"last_change_date": "DESC"},
    )
    op.create_index(
        "ix_projects_partial_type",
        "projects",
        ["type"],
        unique=False,
        postgresql_where=sa.text("type = 'TEMPLATE'"),
    )
    op.create_index(
        "idx_project_to_folders_project_uuid",
        "projects_to_folders",
        ["project_uuid"],
        unique=False,
    )
    op.create_index(
        "idx_project_to_folders_user_id",
        "projects_to_folders",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "idx_projects_to_products_product_name",
        "projects_to_products",
        ["product_name"],
        unique=False,
    )
    op.create_index(
        "idx_workspaces_access_rights_gid",
        "workspaces_access_rights",
        ["gid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_workspaces_access_rights_gid", table_name="workspaces_access_rights"
    )
    op.drop_index(
        "idx_projects_to_products_product_name", table_name="projects_to_products"
    )
    op.drop_index("idx_project_to_folders_user_id", table_name="projects_to_folders")
    op.drop_index(
        "idx_project_to_folders_project_uuid", table_name="projects_to_folders"
    )
    op.drop_index(
        "ix_projects_partial_type",
        table_name="projects",
        postgresql_where=sa.text("type = 'TEMPLATE'"),
    )
    op.drop_index(
        "idx_projects_last_change_date_desc",
        table_name="projects",
        postgresql_using="btree",
        postgresql_ops={"last_change_date": "DESC"},
    )
    op.drop_index("idx_project_to_groups_gid", table_name="project_to_groups")
    # ### end Alembic commands ###
