"""make project owner mandatory

Revision ID: d26057a0f693
Revises: 10729e07000d
Create Date: 2024-10-02 15:30:20.377698+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d26057a0f693"
down_revision = "10729e07000d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "prj_owner", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "prj_owner", nullable=True)
    # ### end Alembic commands ###
