"""added_last_scheduled

Revision ID: da1700f9eceb
Revises: c9db8bf5091e
Create Date: 2024-11-24 17:11:30.519365+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da1700f9eceb"
down_revision = "c9db8bf5091e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comp_runs",
        sa.Column("last_scheduled", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comp_runs", "last_scheduled")
    # ### end Alembic commands ###
