"""add comp runs table

Revision ID: da8abd0d8e42
Revises: ec3ef74cddae
Create Date: 2021-05-12 13:46:36.676255+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "da8abd0d8e42"
down_revision = "ec3ef74cddae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comp_runs",
        sa.Column(
            "run_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            primary_key=True,
        ),
        sa.Column("project_uuid", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("iteration", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "result",
            ENUM(
                "NOT_STARTED",
                "PUBLISHED",
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "ABORTED",
                name="statetype",
                create_type=False,  # necessary to avoid alembic statetype already exists error
            ),
            server_default="NOT_STARTED",
            nullable=False,
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started", sa.DateTime(), nullable=True),
        sa.Column("ended", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_uuid"],
            ["projects.uuid"],
            name="fk_comp_runs_project_uuid_projects",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_comp_runs_user_id_users",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("project_uuid", "user_id", "iteration"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comp_runs")
    # ### end Alembic commands ###
