"""add `enable_efs` to group extra properties

Revision ID: ea3952fe5a0e
Revises: 8a742f3efdd9
Create Date: 2024-10-07 06:24:42.464942+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea3952fe5a0e"
down_revision = "8a742f3efdd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups_extra_properties",
        sa.Column("enable_efs", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups_extra_properties", "enable_efs")
    # ### end Alembic commands ###
