"""New node_class column in comp_tasks

Revision ID: f3555bb4bc34
Revises: 43b26b6e762b
Create Date: 2020-02-28 14:12:14.444624+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3555bb4bc34'
down_revision = '43b26b6e762b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comp_tasks', sa.Column('node_class', sa.Enum('COMPUTATIONAL', 'INTERACTIVE', 'FRONTEND', name='nodeclass'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comp_tasks', 'node_class')
    # ### end Alembic commands ###
