"""add indexes to comp tables

Revision ID: f65f7786cd4b
Revises: cf8f743fd0b7
Create Date: 2025-04-17 12:44:27.577984+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f65f7786cd4b"
down_revision = "cf8f743fd0b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_comp_runs_user_id", "comp_runs", ["user_id"], unique=False)
    op.create_index(
        "ix_comp_tasks_project_id", "comp_tasks", ["project_id"], unique=False
    )
    op.drop_index("idx_projects_last_change_date_desc", table_name="projects")
    op.create_index(
        "idx_projects_last_change_date_desc",
        "projects",
        ["last_change_date"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"last_change_date": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_projects_last_change_date_desc",
        table_name="projects",
        postgresql_using="btree",
        postgresql_ops={"last_change_date": "DESC"},
    )
    op.create_index(
        "idx_projects_last_change_date_desc",
        "projects",
        [sa.text("last_change_date DESC")],
        unique=False,
    )
    op.drop_index("ix_comp_tasks_project_id", table_name="comp_tasks")
    op.drop_index("ix_comp_runs_user_id", table_name="comp_runs")
    # ### end Alembic commands ###
