"""new projects to job map

Revision ID: fbc04f6860cd
Revises: 8403acca8759
Create Date: 2025-03-26 10:49:21.206239+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fbc04f6860cd"
down_revision = "8403acca8759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects_to_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_uuid"],
            ["projects.uuid"],
            name="fk_projects_to_jobs_project_uuid",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_uuid", "job_name", name="uq_projects_to_jobs_project_uuid_job_name"
        ),
        comment="Maps projects.uuid to job_name",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects_to_jobs")
    # ### end Alembic commands ###
