#
# Targets to pip-compile requirements
#
include ../../../scripts/makefiles/requirements.mk

# Add here any extra explicit dependency: e.g. _migration.txt: _base.txt
_packages.txt: _packages.in _base.txt
