#!/bin/bash

# die on non 0 exit code
set -e

FOLDER_CHECKS=(js eslintrc json)

before_install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ops/travis/helpers/show_system_versions
    fi
}

install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        npm install -g npm@latest
        npm install
        cd services/web/client
        npm install
        node_modules/.bin/qx contrib update
        node_modules/.bin/qx contrib install
    fi
}

before_script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        eslint --version
    fi
}

script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        npm run linter
        cd services/web/client
        echo "Building build version"
        node_modules/.bin/qx compile --machine-readable --target=build
        echo "Building source version"
        node_modules/.bin/qx serve --machine-readable --target=source  --listen-port=8080 &
        SERVER_PID=$!
        echo "Waiting for build to complete"
        while ! nc -z localhost 8080; do
          sleep 1 # wait for 10 second before check again
        done
        node build-output/resource/qxl/testtapper/run.js --diag --verbose http://localhost:8080/build/testtapper/
        kill $SERVER_PID
        rm build-output/*.json
    else
        echo "No changes detected. Skipping linting of node.js."
    fi
}

after_success() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        cd services/web/client
        node source-output/resource/qxl/testtapper/run.js http://localhost:8089/testtapper/
        echo "linting successful"
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
