#!/bin/bash

before_install() {
    bash ops/travis/helpers/show_system_versions
}

install() {
    npm install -g npm@latest
    npm install --save-dev eslint
    npm install --save-dev babel-eslint
    npm install --save-dev eslint-config-qx
    npm install --save-dev eslint-plugin-qx-rules
}

before_script() {
    eslint --version
}

script() {
    npm run linter
}

after_success() {
    echo "linting successful"
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi