#!/bin/bash


# die on non 0 exit code
set -e

FOLDER_CHECKS=(packages/ service-library)

before_install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ops/travis/helpers/install_docker_compose
        bash ops/travis/helpers/show_system_versions
    fi
}

install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip install --upgrade pip wheel setuptools && pip3 --version
        pushd packages/service-library; pip3 install -r requirements/ci.txt; popd;
    fi
}

before_script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip list
    fi
}

script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pytest --cov=servicelib --cov-append -v packages/service-library/tests
    else
        echo "No changes detected. Skipping unit-testing of service-library."
    fi
}

after_success() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        coveralls
        codecov
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
