#!/bin/bash

before_install() {    
    bash ops/travis/helpers/install_docker_compose
    bash ops/travis/helpers/show_system_versions
}

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version
    pushd packages/service-library; pip3 install -r requirements/dev.txt; popd
    pip3 install packages/s3wrapper[test]
    pip3 install packages/simcore-sdk[test]
    pip3 install services/storage/client-sdk/python
}

before_script() {
    pip freeze
    make travis-build
    docker images
}

script() {
    pytest --cov=pytest_docker -v packages/pytest_docker/tests
    pytest --cov=s3wrapper -v packages/s3wrapper/tests
    pytest --cov=simcore_sdk -v packages/simcore-sdk/tests
    pytest --cov=servicelib -v packages/service-library/tests
}

after_success() {
    coveralls
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi