#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# in case it's a Pull request, the env are never available, default to itisfoundation to get a maybe not too old version for caching
export DOCKER_IMAGE_TAG=$(exec ci/travis/helpers/build_docker_image_tag)

FOLDER_CHECKS=(packages/ simcore-sdk storage/ simcore-sdk .travis.yml)

before_install() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ci/travis/helpers/install_docker_compose
        bash ci/travis/helpers/show_system_versions
    fi
}

install() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ci/travis/helpers/ensure_python_pip
        pushd packages/simcore-sdk; pip3 install -r requirements/ci.txt; popd;
    fi
}

before_script() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip list -v
        # pull the test images if registry is set up, else build the images
        make pull-version || ((make pull-cache || true) && make build tag-version)
        make info-images
    fi
}

script() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pytest --color=yes --cov=simcore_sdk --cov-append -v packages/simcore-sdk/tests/integration
    else
        echo "No changes detected. Skipping integration-testing of simcore-sdk."
    fi
}

after_success() {
    if bash ci/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        coveralls
        codecov
    fi
}

after_failure() {
    docker images
    make down
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
