from aiohttp import web

from ..constants import FRONTEND_APP_DEFAULT, FRONTEND_APPS_AVAILABLE

STATIC_DIRNAMES = FRONTEND_APPS_AVAILABLE | {"resource", "transpiled"}

FRONTEND_CACHED_INDEXES_APPKEY = web.AppKey("FRONTEND_CACHED_INDEXES", dict)
FRONTEND_CACHED_STATICS_JSON_APPKEY = web.AppKey("FRONTEND_CACHED_STATICS_JSON", dict)
CLIENTAPPS_SETTINGS_APPKEY = web.AppKey("CLIENTAPPS_SETTINGS", dict)


__all__: tuple[str, ...] = (
    "FRONTEND_APPS_AVAILABLE",
    "FRONTEND_APP_DEFAULT",
)

# nopycln: file
