# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class InlineResponseDefaultError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, errors: List[object]=None, message: str=None, status: int=None):  # noqa: E501
        """InlineResponseDefaultError - a model defined in OpenAPI

        :param errors: The errors of this InlineResponseDefaultError.  # noqa: E501
        :type errors: List[object]
        :param message: The message of this InlineResponseDefaultError.  # noqa: E501
        :type message: str
        :param status: The status of this InlineResponseDefaultError.  # noqa: E501
        :type status: int
        """
        self.openapi_types = {
            'errors': List[object],
            'message': str,
            'status': int
        }

        self.attribute_map = {
            'errors': 'errors',
            'message': 'message',
            'status': 'status'
        }

        self._errors = errors
        self._message = message
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponseDefaultError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_default_error of this InlineResponseDefaultError.  # noqa: E501
        :rtype: InlineResponseDefaultError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def errors(self) -> List[object]:
        """Gets the errors of this InlineResponseDefaultError.


        :return: The errors of this InlineResponseDefaultError.
        :rtype: List[object]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[object]):
        """Sets the errors of this InlineResponseDefaultError.


        :param errors: The errors of this InlineResponseDefaultError.
        :type errors: List[object]
        """

        self._errors = errors

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponseDefaultError.

        Error message  # noqa: E501

        :return: The message of this InlineResponseDefaultError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponseDefaultError.

        Error message  # noqa: E501

        :param message: The message of this InlineResponseDefaultError.
        :type message: str
        """

        self._message = message

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponseDefaultError.

        Error code  # noqa: E501

        :return: The status of this InlineResponseDefaultError.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponseDefaultError.

        Error code  # noqa: E501

        :param status: The status of this InlineResponseDefaultError.
        :type status: int
        """

        self._status = status
