from .. import util
from .base_model_ import Model


class InlineResponse2001Authors(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, email: str = None, affiliation: str = None):
        """InlineResponse2001Authors - a model defined in OpenAPI

        :param name: The name of this InlineResponse2001Authors.
        :param email: The email of this InlineResponse2001Authors.
        :param affiliation: The affiliation of this InlineResponse2001Authors.
        """
        self.openapi_types = {"name": str, "email": str, "affiliation": str}

        self.attribute_map = {
            "name": "name",
            "email": "email",
            "affiliation": "affiliation",
        }

        self._name = name
        self._email = email
        self._affiliation = affiliation

    @classmethod
    def from_dict(cls, dikt: dict) -> "InlineResponse2001Authors":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The inline_response_200_1_authors of this InlineResponse2001Authors.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this InlineResponse2001Authors.

        Name of the author

        :return: The name of this InlineResponse2001Authors.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2001Authors.

        Name of the author

        :param name: The name of this InlineResponse2001Authors.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def email(self):
        """Gets the email of this InlineResponse2001Authors.

        Email address

        :return: The email of this InlineResponse2001Authors.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this InlineResponse2001Authors.

        Email address

        :param email: The email of this InlineResponse2001Authors.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def affiliation(self):
        """Gets the affiliation of this InlineResponse2001Authors.

        Affiliation of the author

        :return: The affiliation of this InlineResponse2001Authors.
        :rtype: str
        """
        return self._affiliation

    @affiliation.setter
    def affiliation(self, affiliation):
        """Sets the affiliation of this InlineResponse2001Authors.

        Affiliation of the author

        :param affiliation: The affiliation of this InlineResponse2001Authors.
        :type affiliation: str
        """

        self._affiliation = affiliation
