# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .simcore_node import SimcoreNode  # noqa: F401,E501
from .. import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[SimcoreNode]=None, status: int=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: List[SimcoreNode]
        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type status: int
        """
        self.openapi_types = {
            'data': List[SimcoreNode],
            'status': int
        }

        self.attribute_map = {
            'data': 'data',
            'status': 'status'
        }

        self._data = data
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[SimcoreNode]:
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: List[SimcoreNode]
        """
        return self._data

    @data.setter
    def data(self, data: List[SimcoreNode]):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: List[SimcoreNode]
        """

        self._data = data

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponse2001.


        :return: The status of this InlineResponse2001.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponse2001.


        :param status: The status of this InlineResponse2001.
        :type status: int
        """

        self._status = status
