# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class InlineResponse204(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: str='null', status: int=204):  # noqa: E501
        """InlineResponse204 - a model defined in OpenAPI

        :param data: The data of this InlineResponse204.  # noqa: E501
        :type data: str
        :param status: The status of this InlineResponse204.  # noqa: E501
        :type status: int
        """
        self.openapi_types = {
            'data': str,
            'status': int
        }

        self.attribute_map = {
            'data': 'data',
            'status': 'status'
        }

        self._data = data
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse204':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_204 of this InlineResponse204.  # noqa: E501
        :rtype: InlineResponse204
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> str:
        """Gets the data of this InlineResponse204.


        :return: The data of this InlineResponse204.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this InlineResponse204.


        :param data: The data of this InlineResponse204.
        :type data: str
        """

        self._data = data

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponse204.


        :return: The status of this InlineResponse204.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponse204.


        :param status: The status of this InlineResponse204.
        :type status: int
        """

        self._status = status
