# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class InlineResponse200Data(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_version=None, name=None, status=None, version=None):  # noqa: E501
        """InlineResponse200Data - a model defined in OpenAPI

        :param api_version: The api_version of this InlineResponse200Data.  # noqa: E501
        :type api_version: str
        :param name: The name of this InlineResponse200Data.  # noqa: E501
        :type name: str
        :param status: The status of this InlineResponse200Data.  # noqa: E501
        :type status: str
        :param version: The version of this InlineResponse200Data.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'api_version': 'str',
            'name': 'str',
            'status': 'str',
            'version': 'str'
        }

        self.attribute_map = {
            'api_version': 'api_version',
            'name': 'name',
            'status': 'status',
            'version': 'version'
        }

        self._api_version = api_version
        self._name = name
        self._status = status
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_data of this InlineResponse200Data.  # noqa: E501
        :rtype: InlineResponse200Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self):
        """Gets the api_version of this InlineResponse200Data.


        :return: The api_version of this InlineResponse200Data.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """Sets the api_version of this InlineResponse200Data.


        :param api_version: The api_version of this InlineResponse200Data.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def name(self):
        """Gets the name of this InlineResponse200Data.


        :return: The name of this InlineResponse200Data.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse200Data.


        :param name: The name of this InlineResponse200Data.
        :type name: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this InlineResponse200Data.


        :return: The status of this InlineResponse200Data.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200Data.


        :param status: The status of this InlineResponse200Data.
        :type status: str
        """

        self._status = status

    @property
    def version(self):
        """Gets the version of this InlineResponse200Data.


        :return: The version of this InlineResponse200Data.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this InlineResponse200Data.


        :param version: The version of this InlineResponse200Data.
        :type version: str
        """

        self._version = version
