# coding: utf-8

"""
    simcore-service-storage API

    API definition for simcore-service-storage service  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Contact: support@simcore.io
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from simcore_service_storage_sdk.configuration import Configuration


class HealthCheck(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'status': 'str',
        'api_version': 'str',
        'version': 'str'
    }

    attribute_map = {
        'name': 'name',
        'status': 'status',
        'api_version': 'api_version',
        'version': 'version'
    }

    def __init__(self, name=None, status=None, api_version=None, version=None, local_vars_configuration=None):  # noqa: E501
        """HealthCheck - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._status = None
        self._api_version = None
        self._version = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if api_version is not None:
            self.api_version = api_version
        if version is not None:
            self.version = version

    @property
    def name(self):
        """Gets the name of this HealthCheck.  # noqa: E501


        :return: The name of this HealthCheck.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HealthCheck.


        :param name: The name of this HealthCheck.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this HealthCheck.  # noqa: E501


        :return: The status of this HealthCheck.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this HealthCheck.


        :param status: The status of this HealthCheck.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def api_version(self):
        """Gets the api_version of this HealthCheck.  # noqa: E501


        :return: The api_version of this HealthCheck.  # noqa: E501
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """Sets the api_version of this HealthCheck.


        :param api_version: The api_version of this HealthCheck.  # noqa: E501
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def version(self):
        """Gets the version of this HealthCheck.  # noqa: E501


        :return: The version of this HealthCheck.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this HealthCheck.


        :param version: The version of this HealthCheck.  # noqa: E501
        :type version: str
        """

        self._version = version

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HealthCheck):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HealthCheck):
            return True

        return self.to_dict() != other.to_dict()
