#!/bin/bash
set -e
# Usage:
# test_for_changes ^web/server webserver blah
# this will test if these regexp are part of the modified files since the branching,
# or on the push commit range if running on travis

# detect travis
if [ -z $TRAVIS ] || [ $TRAVIS = "false" ]; then
    CHANGES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))
else
    CHANGES=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE)
fi

# look for changes
for i in .travis.yml ops/travis/.+-testing/ ops/travis/helpers/ "$@"; do
    # echo "checking if last changes contain $i regexp..."
    if egrep -q -- "$i" <<< $CHANGES; then
        echo "changes detected!"
        exit 0
    fi
done

exit 1
