#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

FOLDER_CHECKS=(api/ .travis.yml)

install() {
    bash ci/helpers/ensure_python_pip
    pip3 install --requirement api/tests/requirements.txt
    pip list --verbose
}

test() {
    pytest --cov=api --cov-append --color=yes --cov-report=term-missing --cov-report=xml --verbose api/tests
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
