#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

FOLDER_CHECKS=(api/ apihub .travis.yml)

install() {
    bash ci/helpers/ensure_python_pip
    pip3 install -r api/tests/requirements.txt
    pip3 install -r services/apihub/tests/requirements.txt
    pip list -v
}

test() {
    pytest --cov=api --cov-append --color=yes --cov-report=term-missing --cov-report=xml -v api/tests
    pytest --cov=services_apihub --cov-append  --color=yes --cov-report=term-missing --cov-report=xml -v services/apihub/tests
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
