#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

FOLDER_CHECKS=(api/ sidecar packages/ .travis.yml)

install() {
    bash ci/helpers/ensure_python_pip;
    pushd services/sidecar; pip3 install -r requirements/ci.txt; popd;
    pip list -v
}

test() {
    # TODO: call services/sidecar/tests/unit when integration tests available
    pytest --cov=simcore_service_sidecar --cov-append --cov-report=term-missing --cov-report=xml -v -m "not travis" services/sidecar/tests
    coveralls
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
