#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# in case it's a Pull request, the env are never available, default to itisfoundation to get a maybe not too old version for caching
export DOCKER_IMAGE_TAG=$(exec ci/github/helpers/build_docker_image_tag)

FOLDER_CHECKS=(packages/ simcore-sdk storage/ simcore-sdk .travis.yml)

install() {
    bash ci/travis/helpers/ensure_python_pip
    pushd packages/simcore-sdk; pip3 install -r requirements/ci.txt; popd;
    pip list -v
}

test() {
    pytest --cov=simcore_sdk --cov-append --color=yes --cov-report=term-missing --cov-report=xml -v packages/simcore-sdk/tests/unit
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
