#!/bin/bash

# CHANGES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))
CHANGES=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE) 
echo "$CHANGES"
# MODIFIED=$(grep 'unit-testing\/' <<< "$CHANGES")
#MODIFIED=$(grep '^services\/web' <<< "$CHANGES")
echo "$MODIFIED"
if [ -n "$(grep '^services\/web' <<< "$CHANGES")" ] || [ -n "$(grep 'travis/webserver' <<< "$CHANGES")" ] || [ -n "$(grep '^packages\/' <<< "$CHANGES")" ];
then
    echo "modifications!"
else
    echo "no modifications..."
fi