#!/bin/bash

before_install() {    
    bash ops/travis/helpers/install_docker_compose
    bash ops/travis/helpers/show_system_versions
}

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version
    pushd services/web/server/tests; pip3 install -r requirements.txt; popd
    pushd services/web/server/tests/integration-computation; pip3 install -r requirements.txt; popd
}

before_script() {
    pip freeze
    make travis-build
    docker images
}

script() {
    pytest --cov=simcore_service_webserver -v services/web/server/tests/integration-computation
}

after_success() {
    coveralls
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi