FROM python:3

# Selects appropriate 'server-py-*/' folder
ARG serverdir
ARG web_outdir=/usr/src/app/client

ENV SIMCORE_WEB_OUTDIR=$web_outdir
ENV SIMCORE_WEB_HOSTNAME='0.0.0.0'
ENV DIRECTOR_HOST='http://director-dev'
ENV DIRECTOR_PORT=8001
EXPOSE 8080


WORKDIR /usr/src/app

VOLUME ${SIMCORE_WEB_OUTDIR}
VOLUME /usr/src/app

COPY $serverdir/requirements-dev.txt requirements.txt
RUN python --version \
    && pip3 install --no-cache-dir -r ./requirements.txt \
    && pip list --format=columns

EXPOSE $SIMCORE_WEB_PORT

ENTRYPOINT ["/bin/sh", "-c", "adev runserver --host ${SIMCORE_WEB_HOSTNAME} --port ${SIMCORE_WEB_PORT} --app-factory create_app server.py"]
