#!/bin/bash

before_install() {    
    bash ops/travis/helpers/install_docker_compose
    bash ops/travis/helpers/show_system_versions
}

install() {
    pip3 install --upgrade pip wheel setuptools && pip3 --version
    pip3 install -r ops/travis/system-testing/requirements
    make travis-pull-cache-images
    make build
}

before_script() {
    pip freeze
    docker images
    make up-swarm
}

script() {
    # wait for a minute to let the swarm warm up...
    sleep 1m
    pytest -v ops/travis/system-testing/tests
}

after_success() {
    make down-swarm
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi