#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# only upstream is allowed to push to itisfoundation repo
current_fork=$(echo "${TRAVIS_REPO_SLUG%/*}" | tr '[:upper:]' '[:lower:]')
if [ $current_fork != "itisfoundation" ] &&\
    ([ ! -v DOCKER_REGISTRY ] || [ -z $DOCKER_REGISTRY ] || [ "$DOCKER_REGISTRY" = "itisfoundation" ]); then
    echo "## ERROR: it is not allowed to push to the main dockerhub repository from a fork!"
    echo "## Please adapt your CI-defined environs (DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_REGISTRY)"
    exit 1
fi

# pull the current tested build
export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# re-tag build to master-latest
export DOCKER_IMAGE_TAG=master-latest
make push-version

# re-tag build to master-DATE.BUILD_NUMBER.GIT_SHA
TRAVIS_PLATFORM_VERSION=master-$(date +"%Y-%m-%d").${TRAVIS_BUILD_NUMBER}.$(git rev-parse HEAD)
export DOCKER_IMAGE_TAG=$TRAVIS_PLATFORM_VERSION
make push-version

# show update of images on system
echo "## After push"
make info-images
