#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# pull the current tested build
export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# re-tag build to master-latest
export DOCKER_IMAGE_TAG=master-latest
make push-version

# re-tag build to master-DATE.BUILD_NUMBER.GIT_SHA
TRAVIS_PLATFORM_VERSION=master-$(date +"%Y-%m-%d").${TRAVIS_BUILD_NUMBER}.$(git rev-parse HEAD)
export DOCKER_IMAGE_TAG=$TRAVIS_PLATFORM_VERSION
make push-version

# show update of images on system
echo "## After push"
make info-images
