#!/bin/bash
# as of http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# pull the tagged staging build
# find the docker image tag
export TAG="${TRAVIS_TAG}"
export ORG=${DOCKER_REGISTRY}
export REPO="webserver"
export DOCKER_IMAGE_TAG=$(./ci/helpers/find_staging_version | awk 'END{print}') || exit $?
make pull-version tag-local

# show current images on system
echo "## Before push"
make info-images

# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# re-tag staging to {TRAVIS_TAG}-DATE.BUILD_NUMBER.GIT_SHA
TRAVIS_PLATFORM_PROD_VERSION=${TRAVIS_TAG}-$(date +"%Y-%m-%d").${TRAVIS_BUILD_NUMBER}.$(git rev-parse HEAD)
export DOCKER_IMAGE_TAG=$TRAVIS_PLATFORM_PROD_VERSION
make push-version push-latest

echo "## After push"
make info-images
