#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)

# tags cache and version befor pushing
make tag-cache
make tag-version

# show current images on system
echo "## Before push"
make info-images

# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# push the local cache
make push-cache

# push the local images
make push-version

echo "## After push"
make info-images
