#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# these variable must be available securely from CI
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# only upstream is allowed to push to itisfoundation repo
current_fork=$(echo "${TRAVIS_REPO_SLUG%/*}" | tr '[:upper:]' '[:lower:]')
if [ $current_fork != "itisfoundation" ] &&\
    ([ ! -v DOCKER_REGISTRY ] || [ -z $DOCKER_REGISTRY ] || [ "$DOCKER_REGISTRY" = "itisfoundation" ]); then
    echo "## ERROR: it is not allowed to push to the main dockerhub repository from a fork!"
    echo "## Please adapt your CI-defined environs (DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_REGISTRY)"
    exit 1
fi

export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)

# tags cache and version befor pushing
make tag-cache
make tag-version

# show current images on system
echo "## Before push"
make info-images

# push the local cache
make push-cache

# push the local images
make push-version

echo "## After push"
make info-images
