# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class RegistrationInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email: str=None, password: str=None, username: str=None):  # noqa: E501
        """RegistrationInput - a model defined in OpenAPI

        :param email: The email of this RegistrationInput.  # noqa: E501
        :type email: str
        :param password: The password of this RegistrationInput.  # noqa: E501
        :type password: str
        :param username: The username of this RegistrationInput.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'email': str,
            'password': str,
            'username': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password',
            'username': 'username'
        }

        self._email = email
        self._password = password
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'RegistrationInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegistrationInput of this RegistrationInput.  # noqa: E501
        :rtype: RegistrationInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this RegistrationInput.


        :return: The email of this RegistrationInput.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegistrationInput.


        :param email: The email of this RegistrationInput.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this RegistrationInput.


        :return: The password of this RegistrationInput.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegistrationInput.


        :param password: The password of this RegistrationInput.
        :type password: str
        """

        self._password = password

    @property
    def username(self) -> str:
        """Gets the username of this RegistrationInput.


        :return: The username of this RegistrationInput.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegistrationInput.


        :param username: The username of this RegistrationInput.
        :type username: str
        """

        self._username = username
