""" compose-spec pydantic models


Use this module as facade to import auto-generated model

SEE Makefile recipe to produce _compose_spec_model_autogenerated.py
"""
from typing import TypeAlias

from ._compose_spec_model_autogenerated import (  # type:ignore
    BuildItem,
    ComposeSpecification,
    ListOrDict,
    Service,
    Volume1,
)

SCHEMA_URL = "https://json-schema.org/draft/2019-09/schema#"
SCHEMA_VERSION = SCHEMA_URL.split("/")[-2]


ServiceVolume: TypeAlias = Volume1

__all__: tuple[str, ...] = (
    "BuildItem",
    "ComposeSpecification",
    "ListOrDict",
    "SCHEMA_VERSION",
    "Service",
    "ServiceVolume",
)
# nopycln: file
