from common_library.user_messages import user_message

from ..errors import WebServerBaseError


class StudyDispatcherError(WebServerBaseError, ValueError): ...


class IncompatibleServiceError(StudyDispatcherError):
    msg_template = user_message(
        "None of the registered services can handle '{file_type}'"
    )


class FileToLargeError(StudyDispatcherError):
    msg_template = user_message("File size {file_size_in_mb} MB is over allowed limit")


class ServiceNotFoundError(StudyDispatcherError):
    msg_template = user_message("Service {service_key}:{service_version} not found")


class InvalidRedirectionParamsError(StudyDispatcherError):
    msg_template = "Invalid link"


class GuestUsersLimitError(StudyDispatcherError):
    msg_template = user_message(
        "Maximum number of guests was reached. Please login with a registered user or try again later"
    )


class GuestUserNotAllowedError(StudyDispatcherError):
    msg_template = "Guest users are not allowed to access this resource configuration."


class ProjectWorkbenchMismatchError(StudyDispatcherError):
    msg_template = "Project {project_uuid} exists but does not seem to be a viewer generated by this module"
