#
# DEVELOPMENT recipes for migration
#


include ../../scripts/common.Makefile
include ../../scripts/common-service.Makefile

.PHONY: requirements reqs
requirements reqs: ## (or reqs) compiles pip requirements (.in -> .txt)
	@$(MAKE_C) requirements reqs
