#!/bin/bash
set -e
# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

TRAVIS_PLATFORM_STAGE_VERSION=staging-$(date +"%Y-%m-%d").${TRAVIS_BUILD_NUMBER}.$(git rev-parse HEAD)
export DOCKER_IMAGE_PREFIX=itisfoundation/
export DOCKER_IMAGE_TAG=staging-latest
make tag
make push

export DOCKER_IMAGE_TAG=$TRAVIS_PLATFORM_STAGE_VERSION
make tag
make push
