#!/bin/bash

before_install() {
    ops/travis/generic/show_system_versions
    ops/travis/generic/install_docker_compose
}

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version
    pushd services/storage; pip3 install -r requirements/prod.txt; popd
    pushd services/storage; pip3 install -r tests/requirements.txt; popd
    pip3 install services/storage/client-sdk/python
}

before_script() {
    pip freeze
    make travis-build
    docker images
}

script() {
    pytest --cov=simcore_service_storage -v -m "not travis" services/storage/tests
}

after_success() {
    coveralls
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi