#
# Targets to pip-compile requirements
#
include ../../../requirements/base.Makefile

# Add here any extra explicit dependency: e.g. _migration.txt: _base.txt

_test.txt: _base.txt

_dask-complete.txt: _dask-complete.in _base.txt
_dask-distributed.txt: _dask-distributed.in _base.txt
