#!/bin/bash

before_install() {
    bash ops/travis/generic/show_system_versions
    bash ops/travis/generic/install_docker_compose
}

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version
    pip3 install -r api/tests/requirements.txt
    pip3 install -r services/apihub/tests/requirements.txt
}

before_script() {
    pip freeze
    make travis-build
    docker images
}

script() {
    pytest -v api/tests
    pytest -v services/apihub/tests
}

after_success() {
    coveralls
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi