{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ISAN study hits",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{endpoint=~\"/study/.+\"}",
     "legendFormat": "{{endpoint}}"
    },
    {}
   ]
  },
  {
   "title": "webserver req/sec [10m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=~\"/v0/.+\", http_status=~\"2[0-9]+\", instance=\"webserver:8080\"}[10m])"
    },
    {}
   ]
  },
  {
   "title": "db clients count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"simcoredb\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "storage req/sec [10m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=~\"/v0/.+\", http_status=~\"2[0-9]+\", instance=\"storage:8080\"}[10m])"
    },
    {}
   ]
  }
 ]
}