# coding: utf-8

"""
    simcore-service-storage API

    API definition for simcore-service-storage service  # noqa: E501

    OpenAPI spec version: 0.2.1
    Contact: support@simcore.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import simcore_service_storage_sdk
from simcore_service_storage_sdk.models.presigned_link import (  # noqa: E501
    PresignedLink,
)
from simcore_service_storage_sdk.rest import ApiException


class TestPresignedLink(unittest.TestCase):
    """PresignedLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresignedLink(self):
        """Test PresignedLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = simcore_service_storage_sdk.models.presigned_link.PresignedLink()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
