# coding: utf-8

"""
    simcore-service-storage API

    API definition for simcore-service-storage service  # noqa: E501

    OpenAPI spec version: 0.2.1
    Contact: support@simcore.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import simcore_service_storage_sdk
from simcore_service_storage_sdk.models.health_check_enveloped import (  # noqa: E501
    HealthCheckEnveloped,
)
from simcore_service_storage_sdk.rest import ApiException


class TestHealthCheckEnveloped(unittest.TestCase):
    """HealthCheckEnveloped unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCheckEnveloped(self):
        """Test HealthCheckEnveloped"""
        # FIXME: construct object with mandatory attributes with example values
        # model = simcore_service_storage_sdk.models.health_check_enveloped.HealthCheckEnveloped()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
