#!/bin/bash
# as of http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# pull the tagged master build
export DOCKER_IMAGE_TAG=$(exec ops/travis/helpers/build_docker_image_tag)
make pull

# show current images on system
docker images

# these variable must be available securely from travis
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# re-tag master build to staging-latest
export DOCKER_REGISTRY_NEW=${DOCKER_REGISTRY}
export DOCKER_IMAGE_TAG_NEW=staging-latest
make tag
export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG_NEW}
export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG_NEW}
make push

# re-tag master to staging-DATE.BUILD_NUMBER.GIT_SHA
TRAVIS_PLATFORM_VERSION=staging-$(date +"%Y-%m-%d").${TRAVIS_BUILD_NUMBER}.$(git rev-parse HEAD)
export DOCKER_IMAGE_TAG_NEW=$TRAVIS_PLATFORM_VERSION
make tag
export DOCKER_REGISTRY=${DOCKER_REGISTRY_NEW}
export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG_NEW}
make push
