#
# Targets to pip-compile requirements
#
include ../../../requirements/base.Makefile

# Add here any extra explicit dependency: e.g. _migration.txt: _base.txt


_test.txt: _base.txt _test.in
	@echo INFO: test.txt is frozen. Skipping upgrade.
