#!/bin/bash

before_install() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
        ops/travis/generic/install_docker_compose
        ops/travis/generic/show_system_versions
    fi    
}

install() {
}

before_script() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
        ops/travis/build-cache/pull_cache_builds; 
    fi
}

script() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
        ops/travis/build-cache/build_cache_builds; 
    fi
}

after_success() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
        ops/travis/build-cache/push_cache_builds; 
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi