#!/bin/bash
# as of http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


before_install() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        bash ops/travis/helpers/install_docker_compose;
        bash ops/travis/helpers/show_system_versions;
    fi
}

install() {
    echo "nothing to install..."
}

before_script() {
    echo "nothing to do..."
}

script() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        make build-cache
    fi
}

after_success() {
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        make push-cache
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
