#!/bin/bash

before_install() {
    ops/travis/before_install/show_system_versions
    ops/travis/before_install/install_docker_compose
}

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version
    pushd services/director; pip3 install -r requirements/ci.txt; popd
    pip freeze
}

before_script() {
    pip freeze
    make travis-build
    docker images
}

script() {
    pytest --cov=simcore_service_director -v services/director/tests
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi