#
# Targets to pip-compile requirements
#
include ../../../requirements/base.Makefile

# Add here any extra explicit dependency: e.g. _migration.txt: _base.txt

_base.in: constraints.txt
_test.in: constraints.txt
_tools.in: constraints.txt
