# coding: utf-8

"""
    Director API

    This is the oSparc's director API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@simcore.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import simcore_director_sdk
from simcore_director_sdk.models.inline_response2001_authors import InlineResponse2001Authors  # noqa: E501
from simcore_director_sdk.rest import ApiException


class TestInlineResponse2001Authors(unittest.TestCase):
    """InlineResponse2001Authors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Authors(self):
        """Test InlineResponse2001Authors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = simcore_director_sdk.models.inline_response2001_authors.InlineResponse2001Authors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
