# coding: utf-8

"""
    Director API

    This is the oSparc's director API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@simcore.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import simcore_director_sdk
from simcore_director_sdk.models.services_enveloped import ServicesEnveloped  # noqa: E501
from simcore_director_sdk.rest import ApiException


class TestServicesEnveloped(unittest.TestCase):
    """ServicesEnveloped unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServicesEnveloped(self):
        """Test ServicesEnveloped"""
        # FIXME: construct object with mandatory attributes with example values
        # model = simcore_director_sdk.models.services_enveloped.ServicesEnveloped()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
