#!/bin/bash

install() {
    pip install --upgrade pip wheel setuptools && pip3 --version;
    pip3 install packages/s3wrapper[test];
    pip3 install packages/simcore-sdk[test];
    pip3 install packages/director-sdk/python;
    pushd services/web/server; pip3 install -r requirements/ci.txt; popd;    
}

after_install() {
    pip freeze
}

before_script() {
    make travis-build;
}

script() {
    pytest --cov=simcore_service_webserver -v -m "not travis" services/web/server/tests/unit
    pytest --cov=simcore_service_webserver -v services/web/server/tests/login
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi