import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from ._common import column_created_datetime, column_modified_datetime
from .base import metadata

comp_runs_collections = sa.Table(
    "comp_runs_collections",
    metadata,
    sa.Column(
        "collection_run_id",
        UUID(as_uuid=True),
        server_default=sa.text("gen_random_uuid()"),
        primary_key=True,
    ),
    sa.Column(
        "client_or_system_generated_id",
        sa.String,
        nullable=False,
        doc="Unique identifier for the collection run, generated by the client (ex. Third party using our public api) or system (ex. osparc webserver)",
    ),
    sa.Column(
        "client_or_system_generated_display_name",
        sa.String,
        nullable=False,
    ),
    sa.Column(
        "is_generated_by_system",
        sa.Boolean,
        nullable=False,
    ),
    column_created_datetime(timezone=True),
    column_modified_datetime(timezone=True),
    sa.Index(
        "ix_comp_runs_collections_client_or_system_generated_id",
        "client_or_system_generated_id",
    ),
)
