"""Function api access rights of groups (read, write, execute)"""

import sqlalchemy as sa
from simcore_postgres_database.models._common import (
    RefActions,
    column_created_datetime,
    column_modified_datetime,
)

from .base import metadata

funcapi_api_access_rights_table = sa.Table(
    "funcapi_group_api_access_rights",
    metadata,
    sa.Column(
        "group_id",
        sa.ForeignKey(
            "groups.gid",
            name="fk_func_access_to_groups_group_id",
            onupdate=RefActions.CASCADE,
            ondelete=RefActions.CASCADE,
        ),
        nullable=False,
    ),
    sa.Column(
        "product_name",
        sa.ForeignKey(
            "products.name",
            name="fk_func_access_to_products_product_name",
            onupdate=RefActions.CASCADE,
            ondelete=RefActions.CASCADE,
        ),
        nullable=False,
    ),
    sa.Column(
        "read_functions",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "write_functions",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "execute_functions",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "read_function_jobs",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "write_function_jobs",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "execute_function_jobs",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "read_function_job_collections",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "write_function_job_collections",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    sa.Column(
        "execute_function_job_collections",
        sa.Boolean,
        default=False,
        nullable=False,
    ),
    column_created_datetime(),
    column_modified_datetime(),
    sa.PrimaryKeyConstraint(
        "group_id",
        "product_name",
        name="pk_func_group_product_name_to_api_access_rights",
    ),
)
