# 20180516 - this file not being used yet... placeholder
FROM minio/minio

LABEL maintainer="Elliott Zastrow <ehzastrow@gmail.com>"

ENV MINIO_ACCESS_KEY_FILE=minio_access_key \
    MINIO_SECRET_KEY_FILE=minio_secret_key
