#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
# https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci
set -euo pipefail
IFS=$'\n\t'

# in case it's a Pull request, the env are never available, default to itisfoundation to get a maybe not too old version for caching
export DOCKER_IMAGE_TAG=$(exec ci/travis/helpers/build_docker_image_tag)

before_install() {
    # bash ci/travis/helpers/update_docker
    bash ci/travis/helpers/install_docker_compose
    bash ci/helpers/show_system_versions

    # Enable user namespace cloning
    sysctl kernel.unprivileged_userns_clone=1

    # Launch XVFB
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
}

install() {
    cp tests/e2e/package.json .
    cp tests/e2e/package-lock.json .
    npm install
    make pull-version || ((make pull-cache || true) && make build tag-version)
}

before_script() {
    make info-images
    # disable email registration
    make .env
    echo WEBSERVER_LOGIN_REGISTRATION_INVITATION_REQUIRED=0 >>.env
    echo WEBSERVER_LOGIN_REGISTRATION_CONFIRMATION_REQUIRED=0 >>.env
    make up-version
}

script() {
    # wait for a minute to let the swarm warm up...
    docker service ls --format "table"
    # FIXME: Get rid of this sleep and check the status of the services
    sleep 80s
    make info-swarm
    cp tests/e2e/jest.config.js .
    cp tests/e2e/jest-puppeteer.config.js .
    npm test
}

after_success() {
    # ToDo: call coveralls
    make down
}

after_failure() {
    docker images
    make down
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
