#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
# https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci
set -euo pipefail
IFS=$'\n\t'

# in case it's a Pull request, the env are never available, default to itisfoundation to get a maybe not too old version for caching
export DOCKER_IMAGE_TAG=$(exec ci/github/helpers/build_docker_image_tag)

install() {
    # pull simcore
    make pull-version || ((make pull-cache || true) && make build tag-version)
    make info-images
    # configure simcore for testing with a private registry
    bash tests/e2e/setup_env_insecure_registry
    
    # start simcore
    make up-version

    # create a python venv and activate
    python3 -m venv .venv
    source .venv/bin/activate
    bash ci/helpers/ensure_python_pip

    # install testing framework
    pushd tests/e2e
    make install
    # deploy the registry
    make registry-up
    make wait-for-services

    # prepare registry
    make transfer-images-to-registry
    popd
}

test() {
    pushd tests/e2e; make test; popd
}

clean_up() {
    docker images
    make leave
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
